// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "0xmmq",
            "url": "https://github.com/mmqnym",
            "email": "mail@mmq.dev"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/GoInk/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sample/jwt/get": {
            "get": {
                "description": "This API will generate JWT which users can use on some APIs that require authentication",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Generating JWTs for Authentication",
                "operationId": "v1-sample-generate-jwt",
                "responses": {
                    "200": {
                        "description": "Success\" response=` + "`" + `{\"token\": \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJFeGFtcGxlSWQiLCJleHAiOjE3MTc3NDYyMTUsIm5iZiI6MTcxNzY1OTgxNSwiaWF0IjoxNzE3NjU5ODE1fQ.BOYdOVsiPbK5nfhsYzX4G_EciVlbZ3LM2pCUQFjRwZo\"}` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/response.GenerateJWT"
                        }
                    },
                    "500": {
                        "description": "Failure\" response=` + "`" + `{\"error\": \"something went wrong\"}` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/sample/jwt/test": {
            "post": {
                "description": "This API will check if the JWT is valid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Verifying JWTs",
                "operationId": "v1-sample-test-jwt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success\" response=` + "`" + `{\"userID\": \"ExampleID\"}` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/response.TestJWT"
                        }
                    }
                }
            }
        },
        "/sample/ping": {
            "get": {
                "description": "This API will return 200 if the server is running normally",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Test the server is running normally",
                "operationId": "v1-sample-ping",
                "responses": {
                    "200": {
                        "description": "Success\" response=` + "`" + `{\"message\": \"pong\"}` + "`" + `",
                        "schema": {
                            "$ref": "#/definitions/response.Ping"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "response.GenerateJWT": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "response.Ping": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.TestJWT": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "goink",
	Description:      "GoInk is a template for quickly building a Go web server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
